run_type = "transfer_learning"
device = "cpu"
tb_logdir = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/tl_run/tb_tl"

[parameters]
num_epochs            = 50
save_every_n_epochs   = 5
batch_size            = 64
sample_batch_size     = 1000
input_model_file      = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/reinvent.prior"
output_model_file     = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/tl_run/TL_dasa.model"
smiles_file           = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/dasa_tl_train.smi"
validation_smiles_file = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/dasa_tl_val.smi"
standardize_smiles    = true
randomize_smiles      = true
randomize_all_smiles  = false
internal_diversity    = true
