"""Generate papers.txt: exactly what measured data we have, from which paper.

Written as a script so the accounting cannot drift from notebooks/data/
dasa_literature_seed.csv. Re-run after every seed change.
"""
import csv, os, sys
from collections import defaultdict, Counter
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rdkit import Chem, RDLogger
RDLogger.DisableLog("rdApp.*")

HERE = os.path.dirname(os.path.abspath(__file__))
SEED = os.path.join(HERE, "data", "dasa_literature_seed.csv")
OUT = os.path.join(os.path.dirname(HERE), "papers.txt")

# access status is a fact about us, not about the data, so it lives here
ACCESS = {
    "Hemmer JACS 2018, 140, 10425": ("10.1021/jacs.8b06067", "OPEN via eScholarship qt1vm8m3vt", "read"),

    "Berraud-Pache Chem Sci 2021, 12, 2916": ("10.1039/D0SC06575G", "OPEN (PMC8179403)", "read"),
    "Mallo Chem Sci 2018, 9, 8242": ("10.1039/C8SC03218A", "RSC, Cloudflare-blocked", "NOT read - from project memory"),
    "Peterson Chem Sci 2023, 14, 13025": ("10.1039/D3SC02835F", "OPEN (PMC10664598)", "read"),
    
    "Peterson Chem Commun 2022, 58, 2303": ("10.1039/D1CC06235B", "PAYWALLED - user supplied PDF", "read (main text; ESI NOT seen)"),
    "Blandon-Cumbreras JACS 2026, 148, 130": ("10.1021/jacs.5c19813", "OPEN (PMC12814171)", "read"),
    
    "Nat Commun 2024, hydroxy parents": ("10.1038/s41467-024-49808-7", "OPEN", "NOT re-read - from project memory"),
}
OBS = [("lambda_max_open_nm", "lambda_max"), ("pct_open_equilibrium", "dark equilibrium"),
       ("solvatochromic_slope_nm", "solvatochromic slope"), ("half_life_s", "thermal half-life")]


def main():
    rows = list(csv.DictReader(open(SEED)))
    L = []
    w = L.append
    w("MEASURED DASA DATA — EXACT ACCOUNTING")
    w("=" * 78)
    w("Generated by notebooks/make_papers_txt.py from notebooks/data/dasa_literature_seed.csv.")
    w("Re-run after any seed change. Every number below traces to a named paper and location.")
    w("")

    # --- integrity checks -------------------------------------------------
    smis = [Chem.CanonSmiles(r["smiles_open"]) for r in rows]
    dup = [s for s, n in Counter(smis).items() if n > 1]
    w(f"INTEGRITY: {len(rows)} rows, {len(set(smis))} distinct structures"
      + (f"  ** DUPLICATES: {dup} **" if dup else "  (no duplicates)"))
    formulas = Counter()
    from rdkit.Chem import rdMolDescriptors as rd
    for s in smis:
        formulas[rd.CalcMolFormula(Chem.MolFromSmiles(s))] += 1
    iso = {f: n for f, n in formulas.items() if n > 1}
    w(f"           isomeric pairs sharing a formula (expected, not an error): {iso}")
    w("")

    # --- per paper --------------------------------------------------------
    by = defaultdict(list)
    for r in rows:
        by[r["source"]].append(r)
    w("BY PAPER")
    w("-" * 78)
    for src in sorted(by):
        rs = by[src]
        doi, access, status = ACCESS.get(src, ("?", "?", "?"))
        w(f"\n{src}")
        w(f"   DOI      {doi}")
        w(f"   access   {access}")
        w(f"   status   {status}")
        w(f"   gives    {len(rs)} compound(s): {', '.join(r['compound_id'] for r in rs)}")
        for col, name in OBS:
            n = sum(1 for r in rs if r[col])
            if n:
                w(f"            {n} x {name}")
        conf = Counter(r["structure_confidence"] for r in rs)
        w(f"   structures  {dict(conf)}")

    # --- per observable ---------------------------------------------------
    w("")
    w("BY OBSERVABLE  (this is what a model could actually be trained on)")
    w("-" * 78)
    for col, name in OBS:
        have = [r for r in rs_all(rows) if r[col]]
        w(f"\n{name}: n = {len(have)}")
        if col == "pct_open_equilibrium":
            bys = defaultdict(list)
            for r in have:
                bys[r["equilibrium_solvent"]].append(r["compound_id"])
            for sv, ids in bys.items():
                w(f"   {sv:10s} n={len(ids):2d}  {', '.join(ids)}")
        don = Counter(r["donor_class"] for r in have)
        acc = Counter(r["acceptor_class"] for r in have)
        w(f"   distinct donor classes    {len(don)}  {dict(don)}")
        w(f"   distinct acceptor classes {len(acc)}  {dict(acc)}")
        cert = sum(1 for r in have if r["structure_confidence"] == "certain")
        w(f"   structures certain        {cert}/{len(have)}")

    # --- effective sample size -------------------------------------------
    w("")
    w("EFFECTIVE SAMPLE SIZE — READ THIS BEFORE FITTING ANYTHING")
    w("-" * 78)
    eq = [r for r in rows if r["pct_open_equilibrium"]]
    cdcl3 = [r for r in eq if r["equilibrium_solvent"] == "CDCl3"]
    w(f"The largest single-solvent equilibrium set is CDCl3, n={len(cdcl3)}.")
    w(f"   {sum(1 for r in cdcl3 if r['donor_class']=='fused_aryl')} of those share ONE donor")
    w( "   (2-methylindoline, the Hemmer acceptor series), so they probe the ACCEPTOR")
    w( "   axis only. The donor axis has 2 points (M1 dialkyl, M14 aniline).")
    w( "")
    w( "Count of compounds is NOT the effective sample size. A 9-point series that")
    w( "varies one substituent supports roughly ONE fitted parameter, not nine.")
    w( "Leave-one-out CV within such a series measures interpolation, not")
    w( "generalisation; grouped CV (hold out a whole paper/series) is the honest test.")
    w( "")
    w( "MISSING DATA WE KNOW EXISTS AND HAVE NOT GOT")
    w( "-" * 78)
    w( " * Chem. Commun. 2022 ESI, Fig. 2b / S15: 12 computed ddG values (Me/Et/iPr")
    w( "   at triene positions 1,3,4,5). The only position-resolved ground truth.")
    w( " * Peterson Chem. Sci. 2023 cmpd 1: slope -7 nm, <1% open in MeOH. Structure")
    w( "   not pinned, so it cannot be used.")
    w( " * Stricker Chem 2023 DASA-3: slope -60 nm; donor not stated in the text read.")
    w( " * Hemmer acceptor 8 (hydroxypyridone): 680 nm, 75-85% open; connectivity of")
    w( "   the pyridone not certain from Fig. 1b.")
    w( " * Blandon-Cumbreras CB7/CB8 complexes: t(1/2) 12.4 / 45.1 / 112.2 / 586.3 h.")
    w( "   Host-guest, so not representable as one SMILES.")

    open(OUT, "w").write("\n".join(L) + "\n")
    print("\n".join(L))
    print(f"\nwrote {OUT}")


def rs_all(rows):
    return rows


if __name__ == "__main__":
    main()
