run_type = "transfer_learning"
device = "cpu"
tb_logdir = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/tb_real_tl"
[parameters]
num_epochs = 30
save_every_n_epochs = 30
batch_size = 64
sample_batch_size = 1000
input_model_file = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/reinvent.prior"
output_model_file = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/TL_dasa_real.model"
smiles_file = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/trial_corpus.smi"
validation_smiles_file = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/trial_corpus.smi"
standardize_smiles = true
randomize_smiles = true
