run_type = "staged_learning"
device   = "cpu"
tb_logdir = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/rl_stage2/tb"
json_out_config = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/rl_stage2/_stage2.json"

[parameters]
prior_file         = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/reinvent.prior"
agent_file         = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/tl_run/TL_dasa.model.30.chkpt"
summary_csv_prefix = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/rl_stage2/stage2"
batch_size         = 40
use_checkpoint     = false

[learning_strategy]
type  = "dap"
sigma = 128
rate  = 0.0001

[[stage]]
max_score  = 1.0
max_steps  = 300
chkpt_file = "/Users/hakeemshindy/Downloads/REINVENT4_photochem/outputs_dasa/rl_stage2/stage2.chkpt"

[stage.scoring]
type = "geometric_mean"

[[stage.scoring.component]]
[stage.scoring.component.DASAScaffold]
[[stage.scoring.component.DASAScaffold.endpoint]]
name   = "DASA"
weight = 1.0

[[stage.scoring.component]]
[stage.scoring.component.AqueousSolubility]
[[stage.scoring.component.AqueousSolubility.endpoint]]
name   = "Solubility"
weight = 0.6
params.logs_target = -2.0
params.logs_width  = 1.5
params.logp_max    = 3.0

[[stage.scoring.component]]
[stage.scoring.component.XTBHomoLumo]
[[stage.scoring.component.XTBHomoLumo.endpoint]]
name   = "xTB_Gap"
weight = 0.3
params.gap_min_ev = 1.5
params.gap_max_ev = 2.1

[[stage.scoring.component]]
[stage.scoring.component.DASASwitchability]
[[stage.scoring.component.DASASwitchability.endpoint]]
name   = "WaterSwitch"
weight = 0.8
params.dipole_target_au      = 4.0
params.dipole_sigma_au       = 1.6
params.solv_diff_target_kcal = 0.0
params.solv_diff_sigma_kcal  = 6.0

[diversity_filter]
type        = "IdenticalMurckoScaffold"
bucket_size = 10
minscore    = 0.5

[inception]
smiles_file = ""
memory_size = 100
sample_size = 10
